created delete-the-repo.md
Pradumnasaraf/open-source-with-pradumna pull request #106
Opened 2022-09-08 03:28 UTC by YashPimple

2022-09-11 13:31 UTC, Pradumnasaraf requested changes
Thanks for the PR. Need some minor changes

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Inefficient

2022-09-11 13:31 UTC, Pradumnasaraf commented on pages/How-to/guide/delete-the-repo.md
> +### Deleting a repository
```suggestion
## Deleting a repository
```

2022-09-15 03:59 UTC, kelvinparmar commented on pages/How-to/guide/delete-the-repo.md
> +### Deleting a repository
Should I complete it?

2022-09-18 10:51 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution :tada:!!

2022-09-18 10:52 UTC, merged