Added alt attribute to images in bootcamp section
Pradumnasaraf/open-source-with-pradumna pull request #114
Opened 2022-09-17 20:42 UTC by developer-diganta

## 🛠️ Fixes Issue #107 

## 👨‍💻 Changes proposed
Added alt attribute to the bootcamp section images.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-09-18 11:22 UTC, Pradumnasaraf requested changes
Hey,
Thank you for the PR. There are some changes required to merge this PR successfully.

That causes the image not well-aligned issue
![Screenshot from 2022-09-18 16-50-22](https://user-images.githubusercontent.com/51878265/190899576-fa6ae92b-b32e-4860-a79b-0fa50c502d7e.png)

2022-09-18 11:22 UTC, Pradumnasaraf commented on pages/Bootcamp.md
> +|**Day 8** -  (08-04-2022)|<img src="https://user-images.githubusercontent.com/51878265/162553119-2d600feb-2943-43d6-be71-6acc771cf709.png" alt="Day 8: Branches"height="300">| [`Twitter`](https://twi
```suggestion
|**Day 8** -  (08-04-2022)|<img src="https://user-images.githubusercontent.com/51878265/162553119-2d600feb-2943-43d6-be71-6acc771cf709.png" alt="Day 8: Branches" height="300">| [`Twitter`](https://twitter.com/pradumna_saraf/status/1512331039468756996?s=20&t=WLR8fYIFIzzAxUquYfGIKw) | [`Blog`](https://blog.pradumnasaraf.co/what-are-branches) |
```

2022-09-22 06:28 UTC, developer-diganta commented
@Pradumnasaraf I have done the suggested changes. Can you please check if it works correctly?

2022-09-25 11:19 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-09-25 11:19 UTC, merged