docs : Added process - How to create issue templates (https://github.…
Pradumnasaraf/open-source-with-pradumna pull request #167
Opened 2022-10-02 11:51 UTC by yash251

## 🛠️ Fixes Issue
Closes #65 

## 👨‍💻 Changes proposed
This pull request added content to the [Add issue template](https://oswp.study/#/pages/How-to/guide/adding-issue-template) section in "How to" section of the OSWP site.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-10-02 11:57 UTC, yash251 commented
Hey @Pradumnasaraf when github-actions bot comment 
```
Hey! contributor, thank you for opening a Pull Request 🎉.
Soon one of our maintainers will review it and provide you with feedback/suggestions. If you think it's something urgent, feel free to reach out [Pradumna Saraf](https://twitter.com/home) on Twitter. Star ⭐ this repo to show us support.
Happy, Open Source!
```
The link to your twitter is the home page of twitter. Please update that to your account

2022-10-02 14:06 UTC, Pradumnasaraf commented
> Hey @Pradumnasaraf when github-actions bot comment
> 
> ```
> Hey! contributor, thank you for opening a Pull Request 🎉.
> Soon one of our maintainers will review it and provide you with feedback/suggestions. If you think it's something urgent, feel free to reach out [Pradumna Saraf](https://twitter.com/home) on Twitter. Star ⭐ this repo to show us support.
> Happy, Open Source!
> ```
> 
> The link to your twitter is the home page of twitter. Please update that to your account

Wooh, thank you so much for pointing it out. Will fix that ASAP

2022-10-02 14:10 UTC, Pradumnasaraf requested changes
Hey, You have used the GitHub official docs images that can be subject to copyright. Also we need to explain more in easy way

2022-10-02 14:10 UTC, Pradumnasaraf commented on pages/How-to/guide/adding-issue-template.md
> +You should have a repository. If you don't, go on <u><a href = "https://oswp.study/#/pages/How-to/guide/repo-private-public">this</a></u> page to know how to create a repository.
```suggestion
You should have a repository.
```

2022-10-02 14:10 UTC, Pradumnasaraf commented on pages/How-to/guide/adding-issue-template.md
> +You should have a repository. If you don't, go on <u><a href = "https://oswp.study/#/pages/How-to/guide/repo-private-public">this</a></u> page to know how to create a repository.
That Docs will be for making the repo private/public not for creating a repo. So it will not be suitable.

2022-10-04 18:42 UTC, yash251 commented
Hey @Pradumnasaraf I added my own screenshots and wrote what I did

2022-10-05 17:10 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-05 17:12 UTC, merged

2022-10-05 17:47 UTC, yash251 commented
Is hacktoberfest-accepted label necessary for pr to be valid for Hacktoberfest?

2022-10-07 16:32 UTC, Pradumnasaraf commented
> Is hacktoberfest-accepted label necessary for pr to be valid for Hacktoberfest?

No, but I added it for you :)