Added how to create a repository.
Pradumnasaraf/open-source-with-pradumna pull request #198
Opened 2022-10-08 13:44 UTC by prnvtripathi

## 🛠️ Fixes Issue

closes #181 

## 👨‍💻 Changes proposed

1. Changed [how-to](https://oswp.study/#/pages/How-to/README) page of the site and added a new row in the table at number 11, which links to the page on how to create a repo
2. Added new file in guide folder, create-repo.md
3. Changed link in [process of using github-pages](https://oswp.study/#/pages/How-to/guide/github-pages) in step 1 linking the new *"create repo"* page.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Please tell if any new changes are suggested. :)

2022-10-11 17:25 UTC, Pradumnasaraf requested changes
Hey, thank you for opening the PR.

Here are a couple of changes.
- Add the column to the last of the file in the `How to` `RAEDME` and use this image
![How to process img](https://user-images.githubusercontent.com/51878265/195158675-fb525b73-6a88-4143-bb5d-cd51d50f2a7a.png)
- Center the images in the `create-repo.md` docs

2022-10-11 17:29 UTC, Pradumnasaraf commented on pages/How-to/guide/create-repo.md
> +
```suggestion
#### Step 2

- Give your repository a nice name and description. 
- Choose the repository visibility. Public or Private. Also, it's good to have a README on the project, so check the checkbox.

```

2022-10-12 10:42 UTC, prnvtripathi commented
hey @Pradumnasaraf, please check the changes and suggest if something else is needed

2022-10-12 18:11 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-12 18:13 UTC, merged