Added 'Renaming a Repository' `Closes #194`
Pradumnasaraf/open-source-with-pradumna pull request #210
Opened 2022-10-11 17:09 UTC by nexi9

## 🛠️ Fixes Issue

 Closes #194 

## 👨‍💻 Changes proposed

- Added rename-repo.md, which explains how to rename a repository.
- Added the image link in README.md of How-to section.

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-10-11 17:35 UTC, Pradumnasaraf requested changes
Thank you for the PR. Please remove the extra line and space.

Also can add a line at the bottom, that after you rename the repo, your old repo link will redirect to the new repo link.

2022-10-11 17:35 UTC, Pradumnasaraf commented on pages/How-to/guide/rename-repo.md
> +
```suggestion
```

2022-10-11 17:35 UTC, Pradumnasaraf commented on pages/How-to/guide/rename-repo.md
> +
```suggestion
```

2022-10-11 17:35 UTC, Pradumnasaraf commented on pages/How-to/guide/rename-repo.md
> +
```suggestion
```

2022-10-11 19:23 UTC, nexi9 commented
@Pradumnasaraf kindly check if the changes are satisfactory

2022-10-12 18:18 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-12 18:18 UTC, merged