DOCS: review pr on local system
Pradumnasaraf/open-source-with-pradumna pull request #224
Opened 2022-10-22 18:00 UTC by klaus0512

## 🛠️ Fixes Issue

Closes #223  

## 👨‍💻 Changes proposed

Added a file to the "How to" section to demonstrate how one can Review a PR by taking the code on their system.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-10-22 19:10 UTC, klaus0512 commented
Hey! @Pradumnasaraf, I have linked the PR to the issue.
Kindly review it.

2022-10-23 13:38 UTC, Pradumnasaraf requested changes
Thank you for the PR, Some changes required.

2022-10-23 13:38 UTC, Pradumnasaraf commented on pages/How-to/guide/reviewing-pr-on-our-local-system.md
> +# Congratulation!! You have successfully reviewed a Pull Request on your local system. 🥳🚀
```suggestion
### Congratulation!! You have successfully reviewed a Pull Request on your local system. 🥳🚀
```

2022-10-23 13:38 UTC, Pradumnasaraf commented on pages/How-to/guide/reviewing-pr-on-our-local-system.md
> +# How to review a PR on our local system ?
```suggestion
## How to review a PR on our local system ?
```

2022-10-23 13:38 UTC, Pradumnasaraf commented on pages/How-to/guide/reviewing-pr-on-our-local-system.md
> +# Start Reviewing a PR on our local system.
```suggestion
## Start Reviewing a PR on our local system.
```

2022-10-28 07:42 UTC, klaus0512 commented
Hey, @Pradumnasaraf  
I have resolved the required changes, Kindly review it.

2022-10-31 06:31 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-31 06:32 UTC, merged