Update regular page
Pradumnasaraf/open-source-with-pradumna pull request #238
Opened 2022-12-22 14:57 UTC by lingeshwaran05

## 🛠️ Fixes Issue

#236 

## 👨‍💻 Changes proposed

updated regular page upto dec 22

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-12-22 19:05 UTC, Pradumnasaraf requested changes
Hey, 

 Just need to remove the extra exclamation mark. Also, can you add the ALT text? in place of `[image]`

2022-12-22 19:05 UTC, Pradumnasaraf commented on pages/Regular.md
> +|06 Oct 2022|!![image](https://user-images.githubusercontent.com/76167753/209153790-2b5505a8-e119-4338-b697-4e3d4f882b2b.png)|[`Post Link`](https://twitter.com/pradumna_saraf/status/15778483891605422
```suggestion
|06 Oct 2022|![image](https://user-images.githubusercontent.com/76167753/209153790-2b5505a8-e119-4338-b697-4e3d4f882b2b.png)|[`Post Link`](https://twitter.com/pradumna_saraf/status/1577848389160542209?s=20&t=_eF7n2kPp9v8V5Eja0TGCg)|**Pradumna Saraf** |
```

2022-12-23 14:57 UTC, lingeshwaran05 commented on pages/Regular.md
> +|06 Oct 2022|!![image](https://user-images.githubusercontent.com/76167753/209153790-2b5505a8-e119-4338-b697-4e3d4f882b2b.png)|[`Post Link`](https://twitter.com/pradumna_saraf/status/15778483891605422
yeah sure , thanks for the review

2022-12-23 17:53 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-23 17:53 UTC, merged