update label of icon
Pradumnasaraf/open-source-with-pradumna pull request #38
Opened 2022-05-21 18:19 UTC by KendallDoesCoding

## 🛠️ Fixes Issue
The icon label is not proper.

## 👨‍💻 Changes proposed
- Update icon of label.
- fix grammer probs

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-05-22 11:08 UTC, vikasganiga05 requested changes
I scanned this doc through [Grammarly](https://www.grammarly.com/) and it suggested the following changes. I don't know if it's accurate or not. Just a suggestion.

2022-05-22 11:08 UTC, vikasganiga05 commented on pages/How-to/guide/starting-discussion.md
> +3. If you see the tab near the Pull request or Issues or if the link above, worked, and you want to start a discussion, tap the "New Discussion" icon.
```suggestion
3. If you see the tab near the Pull request or Issues or if the link above worked and want to start a discussion, tap the "New Discussion" icon.
```

2022-05-22 11:08 UTC, vikasganiga05 commented on pages/How-to/guide/starting-discussion.md
> +5. Add title and description of the discussion you want to start.
```suggestion
5. Add a title and description of the discussion you want to start.
```

2022-05-22 11:08 UTC, vikasganiga05 commented on pages/How-to/guide/starting-discussion.md
> +6. Tap "**Start Discussion"** button to open your discussion..
```suggestion
6. Tap the "**Start Discussion"** button to open your discussion...
```

Here are some suggestions from [Grammarly](https://www.grammarly.com/).

2022-05-22 11:33 UTC, KendallDoesCoding commented on pages/How-to/guide/starting-discussion.md
> +## Starting Discussion in GitHub
this one is my bad

2022-05-22 11:35 UTC, KendallDoesCoding commented on pages/How-to/guide/starting-discussion.md
> +2. Besides the **Pull request or Issues icon**, below the repo name, if you see the "Discussions" tap means, that the repo accepts discussions, if you don't see the tab, the repo doesn't accept discu
```suggestion
2. Besides, the **Pull request or Issues icon**, below the repo name, if you see the "Discussions" tap means, that the repo accepts discussions, if you don't see the tab, the repo doesn't accept discussions... If you used the link mentioned above, and it says 404 Page Not Found, means that the repo doesn't accept discussions.
```

2022-05-22 11:36 UTC, KendallDoesCoding commented
How to resolve conflicts?

2022-05-22 12:46 UTC, vikasganiga05 commented
> 



> How to resolve conflicts?

He @KendallDoesCoding , The following resources may help you.
- GitHub Docs &rarr; [Resolving a merge conflict on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
- YouTube Video &rarr; [1.9: Resolving Merge Conflicts - Git and GitHub for Poets](https://youtu.be/JtIX3HJKwfo)

2022-05-22 14:42 UTC, KendallDoesCoding commented
> > 
> 
> > How to resolve conflicts?
> 
> He @KendallDoesCoding , The following resources may help you.
> 
> * GitHub Docs → [Resolving a merge conflict on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
> * YouTube Video → [1.9: Resolving Merge Conflicts - Git and GitHub for Poets](https://youtu.be/JtIX3HJKwfo)

Hi Vikas, Thanks I know how to resolve but it's a little complex for this one

2022-05-22 14:47 UTC, vikasganiga05 commented
> > > 
> > 
> > 
> > > How to resolve conflicts?
> > 
> > 
> > He @KendallDoesCoding , The following resources may help you.
> > 
> > * GitHub Docs → [Resolving a merge conflict on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
> > * YouTube Video → [1.9: Resolving Merge Conflicts - Git and GitHub for Poets](https://youtu.be/JtIX3HJKwfo)
> 
> Hi Vikas, Thanks I know how to resolve but it's a little complex for this one

If possible can you share a screenshot or screen-recording of the conflicts?

2022-05-22 15:33 UTC, KendallDoesCoding commented
> > > > 
> > > 
> > > 
> > > > How to resolve conflicts?
> > > 
> > > 
> > > He @KendallDoesCoding , The following resources may help you.
> > > 
> > > * GitHub Docs → [Resolving a merge conflict on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)
> > > * YouTube Video → [1.9: Resolving Merge Conflicts - Git and GitHub for Poets](https://youtu.be/JtIX3HJKwfo)
> > 
> > 
> > Hi Vikas, Thanks I know how to resolve but it's a little complex for this one
> 
> If possible can you share a screenshot or screen-recording of the conflicts?

![image](https://user-images.githubusercontent.com/84712013/169703369-a9f7b27a-8b72-4aae-8781-4781e4799a4f.png)

2022-05-22 15:57 UTC, vikasganiga05 commented
Hey @KendallDoesCoding , Remove the line from the file. Which is marked red on the below screenshot :point_down: 

![Screenshot](https://user-images.githubusercontent.com/74750414/169704304-45b3eba5-ff8a-4e13-8292-153cd66f99bc.png)

After removing those lines from the file you may see a button like `Mark as resolved` click it. Done :+1:

2022-05-22 17:10 UTC, KendallDoesCoding commented
> Hey @KendallDoesCoding , Remove the line from the file. Which is marked red on the below screenshot 👇
> 
> ![Screenshot](https://user-images.githubusercontent.com/74750414/169704304-45b3eba5-ff8a-4e13-8292-153cd66f99bc.png)
> 
> After removing those lines from the file you may see a button like `Mark as resolved` click it. Done 👍 If you have any queries please let me know.

@vikasganiga05 Thanks a lot for the solution, will do this in the morning.

2022-05-22 17:33 UTC, vikasganiga05 commented
> > Hey @KendallDoesCoding , Remove the line from the file. Which is marked red on the below screenshot point_down
> > ![Screenshot](https://user-images.githubusercontent.com/74750414/169704304-45b3eba5-ff8a-4e13-8292-153cd66f99bc.png)
> > After removing those lines from the file you may see a button like `Mark as resolved` click it. Done +1 If you have any queries please let me know.
> 
> @vikasganiga05 Thanks a lot for the solution, will do this in the morning.

Most welcome :slightly_smiling_face:

2022-05-26 13:06 UTC, KendallDoesCoding commented
A lot has been updated, will re-make the PR.

2022-05-26 13:06 UTC, closed without merging