docs: Add process - "How to create a PR"
Pradumnasaraf/open-source-with-pradumna pull request #56
Opened 2022-06-06 16:00 UTC by gullapalli9482

## 🛠️ Fixes Issue

closes #56

2022-06-06 16:01 UTC, gullapalli9482 commented
I think I did same mistake again,just check it out once , else I'll have to start from beginning again

2022-06-06 16:26 UTC, KendallDoesCoding commented
> I think I did same mistake again,just check it out once , else I'll have to start from beginning again

No, doesn't look like you did the mistake, 2 files have been changed and there are no merge conflicts.

2022-06-06 18:05 UTC, Pradumnasaraf requested changes
Thank you for raising the PR, You don't need to close this PR, you can simply fix this by deleting the file which is not required, I think it's `pages/How-to/guide/2`, and commit it to the same branch from which you created PR. The PR will auto fetch those changes.

If you have doubts feel free to reach out :)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-08 03:35 UTC, gullapalli9482 commented
I hope, I deleted the correct file!

2022-06-09 18:10 UTC, gullapalli9482 commented
Any comments @Pradumnasaraf

2022-06-10 12:35 UTC, Pradumnasaraf commented
So sorry for the delay, I was busy with exams and other stuff 😞

2022-06-10 12:37 UTC, Pradumnasaraf requested changes
Please remove all the extra blank lines
(I am suggesting some of them)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-10 12:37 UTC, Pradumnasaraf commented on pages/How-to/guide/creating-pr.md
> +
```suggestion
```

2022-06-10 12:37 UTC, Pradumnasaraf commented on pages/How-to/guide/creating-pr.md
> +
```suggestion
```

2022-06-10 12:37 UTC, Pradumnasaraf commented on pages/How-to/guide/creating-pr.md
> +
```suggestion
```

2022-06-10 12:37 UTC, Pradumnasaraf commented on pages/How-to/guide/creating-pr.md
> +
```suggestion
```

2022-06-11 03:11 UTC, merged

2022-06-11 03:11 UTC, Pradumnasaraf commented
Thank you for the effort and time. Merged your PR. Good luck for your exams!!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good