Added the issue template
Pradumnasaraf/open-source-with-pradumna pull request #62
Opened 2022-06-12 13:10 UTC by Kanika637

## 🛠️ Fixes Issue

Added the whole procedure of, how to create an issue.

 Closes #18

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-06-12 15:49 UTC, Jai-Solania-29 commented on pages/How-to/guide/adding-issue-template.md
> +-> If you find any bug in the repository feel free to click on `Get Started` and you will get a template in which you will get a template in which you will write a crisp title of the bug and then in
Hey @Kanika637 there is a typo at the last of this line of code. ( Replace ellaborate with elaborate )

2022-06-12 16:01 UTC, Jai-Solania-29 reviewed
Please go through the suggestion made in highlighted area. 
Otherwise everything looks good to me 👍.

2022-06-12 16:49 UTC, Kanika637 commented on pages/How-to/guide/adding-issue-template.md
> +-> If you find any bug in the repository feel free to click on `Get Started` and you will get a template in which you will get a template in which you will write a crisp title of the bug and then in
Thanks for the review @Jai-Solania-29 , will surely correct that typo.

2022-06-13 06:13 UTC, Pradumnasaraf requested changes
Hey! Kanika, thank you so much for your PR and effort!.

**There is some change required:**

 - Instead of storing the Image in the repo physically and using paths to define them, we use `githubusercontent` link once (Which means you can drag and drop the image in the Markdown file it will do rest of this for you)
 
 If you need any help feel to reach out.

2022-06-13 10:38 UTC, Kanika637 commented
@Pradumnasaraf , I actually tried doing the drag and drop thing but, the image gets opened in a new file in the editor (VS code)

2022-06-13 15:25 UTC, Pradumnasaraf commented
> @Pradumnasaraf , I actually tried doing the drag and drop thing but, the image gets opened in a new file in the editor (VS code)

Yes, Kanika you won't be able to do that on VsCode as it's the functionality of Github. You can do the changes here.

2022-06-14 14:12 UTC, Kanika637 commented
I have made the changes @Pradumnasaraf 👍

2022-06-14 17:34 UTC, Pradumnasaraf commented
Hey, @Kanika637 I just noticed you have done a small mistake, you added a guide for "How to create an issue with different templates" not for "how to create the templates for the issue". Yesterday's image was not opening so didn't pay much attention to that.😅


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Not reusable

2022-06-15 10:40 UTC, Kanika637 commented
What to do now? @Pradumnasaraf 😅

2022-06-15 11:11 UTC, Pradumnasaraf commented
> Okay @Pradumnasaraf will do that+1

Thank you,
Also can you please remove the extra line spacing (one is sufficient) because the prettier will throw an error, and also in `<br/>` tags remove trailing `/`, as Hosted markdown doesn't understand that and will throw an error.

2022-06-15 13:15 UTC, Kanika637 commented
I have done all the required changes👍 @Pradumnasaraf

2022-06-15 15:44 UTC, Pradumnasaraf approved these changes
FINALLY!. It's time to merge :) :rocket: 

Thank you so much for your patience and effort, Kanika!! 
(Also, there was some minor refactors left, which I did on your behalf)
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

2022-06-15 15:49 UTC, merged

2022-06-15 16:24 UTC, Kanika637 commented
Thanks for the guidance @Pradumnasaraf 😀

2022-06-15 18:36 UTC, Pradumnasaraf commented
> Thanks for the guidance @Pradumnasaraf 😀

Awesome!!

Your changes are now live on the website link - https://opensource.pradumnasaraf.co/#/pages/How-to/README

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix