docs: Add guide - "how to star a repo"
Pradumnasaraf/open-source-with-pradumna pull request #68
Opened 2022-06-16 12:46 UTC by code-hyker

Closes #66

👨‍💻 Changes proposed

Added the complete procedure for starring a repository along with the necessary screenshots

✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-06-17 17:18 UTC, Pradumnasaraf commented
Hey,
Thank you for opening the PR and for your effort.

There are some changes required.

- bolding on the second line doesn't work 
![Screenshot 2022-06-17 at 10 44 33 PM](https://user-images.githubusercontent.com/51878265/174346835-c812fc16-7acf-4e9c-8e44-376e51f9f323.png)

- Can you make the full or half screenshot, so that beginners can get more clarity. (Suggestion: you can point with a arrow in that screenshot)

2022-06-17 17:19 UTC, Pradumnasaraf requested changes
Hey,
Thank you for opening the PR and for your effort.

There are some changes required.

- bolding on the second line doesn't work 
![Screenshot 2022-06-17 at 10 44 33 PM](https://user-images.githubusercontent.com/51878265/174346835-c812fc16-7acf-4e9c-8e44-376e51f9f323.png)

- Can you make the full or half screenshot, so that beginners can get more clarity. (Suggestion: you can point with an arrow in that screenshot)



__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-17 18:29 UTC, code-hyker commented
The changes have been made.

2022-06-17 18:45 UTC, Pradumnasaraf requested changes
Thank you for the changes, still, some elements are not working on the hosted onw, looks like there is a problem another problem. To temp fix that these changes are necessary. You can see in the image below


![Screenshot 2022-06-18 at 12 12 18 AM](https://user-images.githubusercontent.com/51878265/174362984-644f8b56-57a9-4a0d-89f6-a9c6d6fa91b5.png)

2022-06-17 18:45 UTC, Pradumnasaraf commented on pages/How-to/guide/star-repo.md
> +<br><br><br>
```suggestion

<br><br>
```

2022-06-17 18:45 UTC, Pradumnasaraf commented on pages/How-to/guide/star-repo.md
> +<br><br><br>
```suggestion

<br><br>
```

2022-06-17 18:45 UTC, Pradumnasaraf commented on pages/How-to/guide/star-repo.md
> +<br><br><br>
```suggestion

<br><br>
```

2022-06-17 20:41 UTC, code-hyker commented
I am unable to figure out why is it not working on the hosted one.

2022-06-18 05:58 UTC, Pradumnasaraf commented
> I am unable to figure out why is it not working on the hosted one.

Likewise. Only that particular line is not working. No worries!!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-18 05:59 UTC, Pradumnasaraf approved these changes
Looks good to merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-06-18 07:02 UTC, code-hyker commented
My pleasure!

2022-06-18 09:30 UTC, merged