How to open issues
Pradumnasaraf/open-source-with-pradumna pull request #71
Opened 2022-06-18 18:30 UTC by Prudence97

## 🛠️ Fixes Issue

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2022-06-20 11:02 UTC, Pradumnasaraf requested changes
Hey! thank you for opening the PR and putting in your effort.

The issue you are working on is about how to "assign an issue". So the docs should contain procedures only for that. ( I think we don't need to add steps for `opening and labeling the issue` those are different topics, later on, we can hyperlink those docs in this ).

Some more small changes that are required:
- There is no use of `div` tags, please remove them.
- Instead of using **HTML** tags for headings and paragraphs, please use **Markdown syntax.**
- Only add a single blank spaced line.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-10 11:02 UTC, Pradumnasaraf commented
Hey @Prudence97 waiting for your changes!!

2022-08-02 16:01 UTC, Kanika637 commented on pages/How-to/guide/assigning-issue.md
> +  <p> Issues are important as they alert a maintainer to review and make new changes or receive information. These Information could include bugs, new ideas, feedback etc.
There are some spelling mistakes which you can take care of like "Information" should be "information".

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Unreadable

2022-08-02 16:02 UTC, Kanika637 commented on pages/How-to/guide/assigning-issue.md
> +They are also a number of ways to creating an issue from a GitHub repository.
"They" should be "There"

2022-08-02 16:04 UTC, Kanika637 commented on pages/How-to/guide/assigning-issue.md
> +Until later
I think the steps you have written for the process don't have the required spacing, the steps are getting camouflaged with the screenshots.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-02 18:55 UTC, Jai-Solania-29 commented
Hey @Prudence97 I went through the changed file and I found many grammatical mistakes, so I would recommend you to double-check once before making a PR.

2022-08-04 13:21 UTC, Pradumnasaraf commented
Thank you @Kanika637 for the review. I have made the suggested changes. I think this doc still needs improvement If you want to improve free to raise a PR.

2022-08-04 13:25 UTC, Pradumnasaraf approved these changes
Looks goog to merge!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

2022-08-04 13:26 UTC, merged